Repository mash-up-kr/Dorabangs_Android, pull requests merged in 2024-08, with the labels that each got.

#110 [feature] 삭제 기능 추가
  data/src/main/kotlin/com/mashup/dorabangs/data/repository/AIClassificationRepositoryImpl.kt
  domain/src/main/kotlin/com/mashup/dorabangs/domain/repository/AIClassificationRepository.kt
  domain/src/main/kotlin/com/mashup/dorabangs/domain/usecase/aiclassification/DeletePostFromAIClassificationUseCase.kt
  feature/classification/src/main/java/com/mashup/feature/classification/ClassificationListScreen.kt
  feature/classification/src/main/java/com/mashup/feature/classification/ClassificationScreen.kt
  feature/classification/src/main/java/com/mashup/feature/classification/ClassificationState.kt
  feature/classification/src/main/java/com/mashup/feature/classification/ClassificationViewModel.kt
Labels: feature

#114 [feature] 다시 태어나보니 폴더 [한개] 이동을 할수 있었던 건에 대하여...
  data/src/main/kotlin/com/mashup/dorabangs/data/datasource/remote/api/AIClassificationRemoteDataSource.kt
  data/src/main/kotlin/com/mashup/dorabangs/data/datasource/remote/impl/AIClassificationRemoteDataSourceImpl.kt
  data/src/main/kotlin/com/mashup/dorabangs/data/network/service/AIClassificationService.kt
  data/src/main/kotlin/com/mashup/dorabangs/data/repository/AIClassificationRepositoryImpl.kt
  domain/src/main/kotlin/com/mashup/dorabangs/domain/repository/AIClassificationRepository.kt
  domain/src/main/kotlin/com/mashup/dorabangs/domain/usecase/aiclassification/MoveSinglePostToRecommendedFolderUseCase.kt
  feature/classification/src/main/java/com/mashup/feature/classification/ClassificationListScreen.kt
  feature/classification/src/main/java/com/mashup/feature/classification/ClassificationScreen.kt
  feature/classification/src/main/java/com/mashup/feature/classification/ClassificationViewModel.kt
  feature/storage/src/main/java/com/mashup/dorabangs/feature/storage/storagedetail/model/StorageDetailSort.kt
Labels: feature

#121 AI분류 디자인 적용 레츠고
  core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/buttons/ButtonType.kt
  core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/buttons/GradientButton.kt
  core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/theme/Colors.kt
  feature/classification/src/main/java/com/mashup/feature/classification/ClassificationListScreen.kt
  feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeScreen.kt
Labels: feature

#119 클라에게 웹뷰란....?
  app/build.gradle.kts
  app/src/main/java/com/mashup/dorabangs/navigation/MainNavHost.kt
  core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/card/FeedCard.kt
  core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/card/FeedCardUiModel.kt
  core/navigation/src/main/java/com/mashup/core/navigation/NavigationRoute.kt
  core/webview/.gitignore
  core/webview/build.gradle.kts
  core/webview/consumer-rules.pro
  core/webview/proguard-rules.pro
  core/webview/src/androidTest/java/com/mashup/dorabangs/core/webview/ExampleInstrumentedTest.kt
  core/webview/src/main/AndroidManifest.xml
  core/webview/src/main/java/com/mashup/dorabangs/core/webview/DoraWebView.kt
  core/webview/src/main/java/com/mashup/dorabangs/core/webview/WebViewNavigation.kt
  core/webview/src/test/java/com/mashup/dorabangs/core/webview/ExampleUnitTest.kt
  data/src/main/kotlin/com/mashup/dorabangs/data/model/classification/AIClassificationAIPostListResponseModel.kt
  domain/src/main/kotlin/com/mashup/dorabangs/domain/model/classification/AIClassificationFeedPost.kt
  feature/classification/src/main/java/com/mashup/feature/classification/ClassificationListScreen.kt
  feature/classification/src/main/java/com/mashup/feature/classification/ClassificationScreen.kt
  feature/classification/src/main/java/com/mashup/feature/classification/ClassificationViewModel.kt
  feature/classification/src/main/java/com/mashup/feature/classification/navigation/ClassificationNavigation.kt
  feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeScreen.kt
  feature/home/src/main/java/com/mashup/dorabangs/feature/model/MapperExtensions.kt
  feature/home/src/main/java/com/mashup/dorabangs/feature/navigation/HomeNavigation.kt
  feature/storage/src/main/java/com/mashup/dorabangs/feature/navigation/StorageDetailNavigation.kt
  feature/storage/src/main/java/com/mashup/dorabangs/feature/storage/storagedetail/StorageDetail.kt
  feature/storage/src/main/java/com/mashup/dorabangs/feature/storage/storagedetail/StorageDetailList.kt
  feature/storage/src/main/java/com/mashup/dorabangs/feature/storage/storagedetail/model/PostCardMapper.kt
  settings.gradle.kts
Labels: feature

#116 홈화면에서 드디어 폴더 이동을 할 수 있게되었다는...소문이...
  app/src/main/java/com/mashup/dorabangs/navigation/MainNavHost.kt
  core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/bottomsheet/BottomSheetType.kt
  core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/card/FeedCard.kt
  feature/home/src/main/java/com/mashup/dorabangs/feature/createfolder/HomeCreateFolderScreen.kt
  feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeContract.kt
  feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeSideEffect.kt
  feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeViewModel.kt
  feature/home/src/main/java/com/mashup/dorabangs/feature/navigation/HomeCreateFolderNavigation.kt
  feature/storage/src/main/java/com/mashup/dorabangs/feature/storage/storagedetail/StorageDetail.kt
Labels: feature

#134 [fix] 여러개 마~~~악 누르면 안사라지는 버그 수정
  app/src/main/java/com/mashup/dorabangs/DoraOverlayService.kt
  data/src/main/kotlin/com/mashup/dorabangs/data/datasource/remote/api/AIClassificationRemoteDataSource.kt
  data/src/main/kotlin/com/mashup/dorabangs/data/network/service/AIClassificationService.kt
Labels: bug

#140 [fix] 크래시 대응
  app/src/main/java/com/mashup/dorabangs/DoraShareActivity.kt
Labels: bug

#176 [feature] 공통화 및 aab 추가, 병렬 실행
  .github/workflows/build.yaml
  .github/workflows/common-setup.yaml
  .github/workflows/create_artifact.yaml
  .github/workflows/lint_check.yaml
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: feature

#181 웹뷰 cleartext_not_permitted 적용
  app/src/main/AndroidManifest.xml
Labels: QA

#180 홈화면 피드 카테고리 추가 및 썸네일 radius 적용
  core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/card/FeedCard.kt
  data/src/main/kotlin/com/mashup/dorabangs/data/model/PostResponseModel.kt
  feature/home/src/main/java/com/mashup/dorabangs/feature/model/MapperExtensions.kt
  feature/storage/src/main/java/com/mashup/dorabangs/feature/storage/storagedetail/model/PostCardMapper.kt
Labels: QA

#171 [QA] 홈, 보관함 토스트 관련 QA 수정
  app/src/main/java/com/mashup/dorabangs/navigation/MainNavHost.kt
  core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/bottomsheet/BottomSheetType.kt
  core/designsystem/src/main/java/com/mashup/dorabangs/core/designsystem/component/bottomsheet/DoraBottomSheetItem.kt
  feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeContract.kt
  feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeSideEffect.kt
  feature/home/src/main/java/com/mashup/dorabangs/feature/home/HomeViewModel.kt
  feature/home/src/main/java/com/mashup/dorabangs/feature/navigation/HomeNavigation.kt
  feature/home/src/main/res/values/string.xml
  feature/storage/src/main/java/com/mashup/dorabangs/feature/folders/FolderManageSideEffect.kt
  feature/storage/src/main/java/com/mashup/dorabangs/feature/folders/FolderManageViewModel.kt
  feature/storage/src/main/java/com/mashup/dorabangs/feature/folders/StorageFolderManageScreen.kt
  feature/storage/src/main/java/com/mashup/dorabangs/feature/navigation/FolderManageNavigation.kt
  feature/storage/src/main/java/com/mashup/dorabangs/feature/navigation/StorageDetailNavigation.kt
  feature/storage/src/main/java/com/mashup/dorabangs/feature/storage/storagedetail/StorageDetail.kt
  feature/storage/src/main/java/com/mashup/dorabangs/feature/storage/storagedetail/StorageDetailViewModel.kt
  feature/storage/src/main/java/com/mashup/dorabangs/feature/storage/storagedetail/model/StorageDetailSideEffect.kt
  feature/storage/src/main/java/com/mashup/dorabangs/feature/storage/storagedetail/model/StorageDetailState.kt
Labels: feature

#191 [fix] 잘안되던 오토태깅 수정
  .github/workflows/auto-tagging.yaml
Labels: patch

#196 [version_up] ci 수정사항 테스트 겸 버전업
  .github/workflows/auto-tagging.yaml
  .github/workflows/create_artifact.yaml
  app/build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/GitUtil.kt
  gradle/libs.versions.toml
Labels: patch
